import "./globals.css";
import Header from "@/components/RootLayout/Header";
import Footer from "@/components/RootLayout/footer/Footer";

import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Liquor store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
