import { i18n } from "@/i18.config";
import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Liquor store",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((lang) => ({ locale: lang }));
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
