import { ReactNode } from "react";
import "./globals.css";
import localFont from "next/font/local";
import { Providers } from "./providers";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { unstable_setRequestLocale } from "next-intl/server";
import { UserProvider } from "@auth0/nextjs-auth0/client";

interface RootLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
  };
}

export const metadata = {
  title: "Liquor store",
  description: "Generated by create next app",
};

const myFont = localFont({ src: "../../public/Assets/fonts/file.woff2" });

export function generateStaticParams() {
  return ["en", "ka"].map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  unstable_setRequestLocale(locale);
  const messages = useMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <UserProvider>
        <body className="dark:bg-gray">
          <main className={myFont.className}>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <Providers>{children}</Providers>
            </NextIntlClientProvider>
          </main>
        </body>
      </UserProvider>
    </html>
  );
}
